#!/usr/bin/env python3
"""Render a curated set of Material icons to Pebble PNG resources for the
per-habit icon on the Habits list.

Source font + codepoints ship with the Flutter SDK cache (Apache-2.0). We only
rasterise the names in ICON_NAMES, at SIZE px, black-on-transparent, under
resources/images/hi/. Habit rows are black-on-white / black-on-cerulean, never
inverted, so no white variant is needed.

Also emits:
  - scripts/habit-icons.media.json : the "media" entries to splice into package.json
  - src/c/habit_icons.h            : the name -> RESOURCE_ID table the watch reads

Re-run whenever ICON_NAMES changes. Requires Pillow.
"""
import json
import os

from PIL import Image, ImageFont, ImageDraw

FONT = "/opt/flutter/bin/cache/artifacts/material_fonts/MaterialIcons-Regular.otf"
CODEPOINTS = "/opt/flutter/bin/cache/artifacts/material_fonts/codepoints"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "resources", "images", "hi")
SIZE = 20  # box the glyph is fitted into; matches the habit-row icon slot

# Material icon name (as Super Productivity stores it) -> our short key. The key
# is the resource id suffix and the string the phone sends in HABIT_ICON.
ICON_NAMES = [
    "directions_walk", "directions_run", "directions_bike", "fitness_center",
    "self_improvement", "pool", "sports_gymnastics", "sports_soccer",
    "free_breakfast", "local_cafe", "restaurant", "local_bar", "no_drinks",
    "water_drop", "bedtime", "medication", "local_florist", "park", "pets",
    "book", "menu_book", "school", "edit", "brush", "code", "language",
    "music_note", "smoke_free", "favorite", "star", "wb_sunny", "nightlight",
    "cleaning_services", "savings", "shopping_cart", "phone_iphone",
]


def load_codepoints():
    cp = {}
    with open(CODEPOINTS) as fh:
        for line in fh:
            parts = line.split()
            if len(parts) == 2:
                cp[parts[0]] = int(parts[1], 16)
    return cp


def render(char, fill):
    img = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    # Fit the glyph: Material glyphs are designed on a 24px em, draw at SIZE+4
    # and trim so odd metrics still land centred.
    font = ImageFont.truetype(FONT, SIZE + 4)
    big = Image.new("RGBA", (SIZE + 8, SIZE + 8), (0, 0, 0, 0))
    ImageDraw.Draw(big).text((4, 2), char, font=font, fill=fill + (255,))
    bbox = big.getbbox()
    if bbox:
        glyph = big.crop(bbox)
        glyph.thumbnail((SIZE, SIZE), Image.LANCZOS)
        img.paste(glyph, ((SIZE - glyph.width) // 2, (SIZE - glyph.height) // 2), glyph)
    # Keep the anti-aliased alpha: basalt/chalk/emery are 64-colour and render it
    # smoothly; diorite (1-bit) thresholds it itself. A gentle lift so faint
    # edges from the downscale don't disappear entirely.
    r, g, b, a = img.split()
    a = a.point(lambda v: 0 if v < 24 else min(255, int(v * 1.35)))
    return Image.merge("RGBA", (r, g, b, a))


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    cp = load_codepoints()
    media = []
    table = []
    missing = []
    for name in ICON_NAMES:
        code = cp.get(name + "_baseline") or cp.get(name)
        if not code:
            missing.append(name)
            continue
        char = chr(code)
        slug = name.replace("_", "-")
        render(char, (0, 0, 0)).save(os.path.join(OUT_DIR, slug + ".png"))
        res = "IMAGE_HI_" + name.upper()
        media.append({
            "type": "bitmap",
            "name": res,
            "file": "images/hi/" + slug + ".png",
            # aplite draws no per-habit icon (the whole feature is non-aplite);
            # keep them out of its pbpack.
            "targetPlatforms": ["basalt", "chalk", "diorite", "emery"],
        })
        table.append((name, res))

    with open(os.path.join(ROOT, "scripts", "habit-icons.media.json"), "w") as fh:
        json.dump(media, fh, indent=2)

    with open(os.path.join(ROOT, "src", "c", "habit_icons.h"), "w") as fh:
        fh.write("// Generated by scripts/gen-habit-icons.py - do not edit.\n")
        fh.write("// Material icon name (as Super Productivity stores it) -> bitmap resource.\n")
        fh.write("#pragma once\n\n")
        fh.write("typedef struct { const char *name; uint32_t res; } HabitIcon;\n\n")
        fh.write("static const HabitIcon HABIT_ICONS[] = {\n")
        for name, res in table:
            fh.write('  { "%s", RESOURCE_ID_%s },\n' % (name, res))
        fh.write("};\n")
        fh.write("#define HABIT_ICON_COUNT %d\n" % len(table))

    print("rendered %d icons" % len(table))
    if missing:
        print("MISSING codepoints (skipped):", ", ".join(missing))


if __name__ == "__main__":
    main()
