// Generated by scripts/gen-habit-icons.py - do not edit.
// Material icon name (as Super Productivity stores it) -> bitmap resource.
#pragma once

typedef struct { const char *name; uint32_t res; } HabitIcon;

static const HabitIcon HABIT_ICONS[] = {
  { "directions_walk", RESOURCE_ID_IMAGE_HI_DIRECTIONS_WALK },
  { "directions_run", RESOURCE_ID_IMAGE_HI_DIRECTIONS_RUN },
  { "directions_bike", RESOURCE_ID_IMAGE_HI_DIRECTIONS_BIKE },
  { "fitness_center", RESOURCE_ID_IMAGE_HI_FITNESS_CENTER },
  { "self_improvement", RESOURCE_ID_IMAGE_HI_SELF_IMPROVEMENT },
  { "pool", RESOURCE_ID_IMAGE_HI_POOL },
  { "sports_gymnastics", RESOURCE_ID_IMAGE_HI_SPORTS_GYMNASTICS },
  { "sports_soccer", RESOURCE_ID_IMAGE_HI_SPORTS_SOCCER },
  { "free_breakfast", RESOURCE_ID_IMAGE_HI_FREE_BREAKFAST },
  { "local_cafe", RESOURCE_ID_IMAGE_HI_LOCAL_CAFE },
  { "restaurant", RESOURCE_ID_IMAGE_HI_RESTAURANT },
  { "local_bar", RESOURCE_ID_IMAGE_HI_LOCAL_BAR },
  { "no_drinks", RESOURCE_ID_IMAGE_HI_NO_DRINKS },
  { "water_drop", RESOURCE_ID_IMAGE_HI_WATER_DROP },
  { "bedtime", RESOURCE_ID_IMAGE_HI_BEDTIME },
  { "medication", RESOURCE_ID_IMAGE_HI_MEDICATION },
  { "local_florist", RESOURCE_ID_IMAGE_HI_LOCAL_FLORIST },
  { "park", RESOURCE_ID_IMAGE_HI_PARK },
  { "pets", RESOURCE_ID_IMAGE_HI_PETS },
  { "book", RESOURCE_ID_IMAGE_HI_BOOK },
  { "menu_book", RESOURCE_ID_IMAGE_HI_MENU_BOOK },
  { "school", RESOURCE_ID_IMAGE_HI_SCHOOL },
  { "edit", RESOURCE_ID_IMAGE_HI_EDIT },
  { "brush", RESOURCE_ID_IMAGE_HI_BRUSH },
  { "code", RESOURCE_ID_IMAGE_HI_CODE },
  { "language", RESOURCE_ID_IMAGE_HI_LANGUAGE },
  { "music_note", RESOURCE_ID_IMAGE_HI_MUSIC_NOTE },
  { "smoke_free", RESOURCE_ID_IMAGE_HI_SMOKE_FREE },
  { "favorite", RESOURCE_ID_IMAGE_HI_FAVORITE },
  { "star", RESOURCE_ID_IMAGE_HI_STAR },
  { "wb_sunny", RESOURCE_ID_IMAGE_HI_WB_SUNNY },
  { "nightlight", RESOURCE_ID_IMAGE_HI_NIGHTLIGHT },
  { "cleaning_services", RESOURCE_ID_IMAGE_HI_CLEANING_SERVICES },
  { "savings", RESOURCE_ID_IMAGE_HI_SAVINGS },
  { "shopping_cart", RESOURCE_ID_IMAGE_HI_SHOPPING_CART },
  { "phone_iphone", RESOURCE_ID_IMAGE_HI_PHONE_IPHONE },
};
#define HABIT_ICON_COUNT 36
